version: "3.8"

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    # security_opt:
    #   - no-new-privileges:true
    pids_limit: 100
    ports:
      - 5432:5432
    volumes:
      # - ./db/data-14:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user_password
      - POSTGRES_DB=godopudb
